"""Calculate the electrical properties of superconductors using Mattis-Bardeen
theory.

The integrals from the Mattis-Bardeen paper are evaluated with adaptive
quadrature after a change of variables that removes the inverse-square-root
endpoint singularities.

References:

    [1] A. R. Kerr, “Surface Impedance of Superconductors and Normal
    Conductors in EM Simulators,” Green Bank, West Virginia, 1996.

    [2] V. Y. Belitsky and E. L. Kollberg, “Superconductor–insulator–
    superconductor tunnel strip line: Features and applications,” J.
    Appl. Phys., vol. 80, no. 8, pp. 4741–4748, Oct. 1996.

"""

from copy import deepcopy

import numpy as np
import scipy.constants as sc
from scipy.integrate import quad


# Constants (all energies in eV)
kb = sc.k / sc.e
h = sc.h / sc.e
hbar = sc.h / (2 * sc.pi) / sc.e


# Integration tolerances (passed to scipy.integrate.quad)
_EPSABS = 1.49e-8
_EPSREL = 1.49e-8


# Default parameters (for niobium, from [2])
PARAM = dict(Tc       = 9.0,         # Critical temperature [K]
             Vgap0    = 2.862e-3,    # Gap voltage at T=0K [V]
             sigma_n  = 1.565e7,     # Normal-state conductivity [1/ohm*m]
             lambda0  = 85*sc.nano,  # London penetration depth at T=0K [m]
            )


# Conductance ----------------------------------------------------------------

def conductance(f, T, Vgap, **kwargs):
    """Calculate conductance from Mattis-Bardeen theory.

    Args:
        f (ndarray): frequency, in units [Hz]
        T (float): temperature, in units [K]

    Keyword arguments:
        Tc (float): critical temperature, in units [K]
        Vgap0 (float): gap voltage at T=0K, in units [V]
        sigma_n (float): normal-state conductance, in units [1/ohm*m]
        lambda0 (float): London penetration depth at T=0K, in units [m]

    Returns:
        conductance

    """

    # Import keyword arguments
    tmp = deepcopy(PARAM)
    tmp.update(kwargs)
    kw = tmp

    if isinstance(f, float) or isinstance(f, int):
        sigma = _conductance(f, T, Vgap, **kw)
        return sigma
    elif isinstance(f, np.ndarray):
        sigma = np.empty_like(f, dtype=complex)
        for i in range(len(f)):
            sigma[i] = _conductance(f[i], T, Vgap, **kw)
        return sigma
    else:
        raise ValueError


def _conductance(f, T, Vgap, **kwargs):
    """Calculate conductance from Mattis-Bardeen theory at a single frequency
    point.

    Args:
        f (float): frequency, in units [Hz]
        T (float): temperature, in units [K]

    Keyword arguments:
        Tc (float): critical temperature, in units [K]
        Vgap0 (float): gap voltage at T=0K, in units [V]
        sigma_n (float): normal-state conductance, in units [1/ohm*m]
        lambda0 (float): London penetration depth at T=0K, in units [m]

    Returns:
        conductance

    """

    # Unpack keyword arguments
    # tc = kwargs['Tc']
    sigma_n = kwargs['sigma_n']

    # Other parameters
    delta = Vgap / 2   # binding energy
    fgap = Vgap / h    # gap frequency
    w = 2 * sc.pi * f  # angular frequency of signal

    # It's a superconductor -> infinite conductivity at f=0Hz
    if f == 0:
        return sigma_n * (1e10 - 1j * 1e10)

    hw = hbar * w  # photon energy

    # Each integrand below is the corresponding integrand from the Mattis-
    # Bardeen paper after a change of variables that cancels the 1/sqrt
    # endpoint singularities, leaving a smooth function for quad.

    # Thermal contribution ---------------------------------------------------
    # Contribution from thermally excited quasi-particles:
    #   int_delta^inf [f(E) - f(E+hw)] g(E) dE
    # Substitute E = delta*cosh(theta): dE cancels sqrt(E^2 - delta^2), and
    # the Fermi factors cut off the integrand at high energy, so the upper
    # limit can be truncated where fermi(E, T) underflows to zero.

    def _thermal(theta):
        e = delta * np.cosh(theta)
        return (fermi(e, T) - fermi(e + hw, T)) * \
               (e**2 + delta**2 + hw*e) / np.sqrt((e + hw)**2 - delta**2)

    if T == 0:
        # No thermally excited quasi-particles at T=0
        thermal = 0.
    else:
        e_max = delta + 60 * kb * T
        theta_max = np.arccosh(e_max / delta)
        thermal = 2 / hw * quad(_thermal, 0, theta_max,
                                epsabs=_EPSABS, epsrel=_EPSREL)[0]

    # Radiation contribution -------------------------------------------------
    # Contribution from quasi-particles generated by radiation (f>fgap):
    #   int_{delta-hw}^{-delta} [1 - 2f(E+hw)] g(E) dE
    # Substitute E = c + r*sin(theta): dE cancels the singular factors at
    # both endpoints, leaving sqrt((delta-E)(E+hw+delta)) >= 2*delta.

    if f > fgap:
        a, b = delta - hw, -delta
        c, r = (a + b) / 2, (b - a) / 2

        def _radiation(theta):
            e = c + r * np.sin(theta)
            return (1 - 2 * fermi(e + hw, T)) * \
                   np.abs(e**2 + delta**2 + hw*e) / \
                   np.sqrt((delta - e) * (e + hw + delta))

        radiation = 1 / hw * quad(_radiation, -np.pi/2, np.pi/2,
                                  epsabs=_EPSABS, epsrel=_EPSREL)[0]
    else:
        radiation = 0

    # Cooper pair contribution -----------------------------------------------
    #   int_a^delta [1 - 2f(E+hw)] (E^2+delta^2+hw*E) /
    #       (sqrt(delta^2-E^2) sqrt((E+hw)^2-delta^2)) dE
    # with a = max(delta-hw, -delta). Same sine substitution; the smooth
    # factor left in the denominator depends on which limit applies.

    a, b = max(delta - hw, -delta), delta
    c, r = (a + b) / 2, (b - a) / 2

    if f > fgap:
        def _smooth(e):
            return np.sqrt((e + hw - delta) * (e + hw + delta))
    else:
        def _smooth(e):
            return np.sqrt((delta + e) * (e + hw + delta))

    def _cooper(theta):
        e = c + r * np.sin(theta)
        return (1 - 2 * fermi(e + hw, T)) * \
               (e**2 + delta**2 + hw*e) / _smooth(e)

    cooper = 1 / hw * quad(_cooper, -np.pi/2, np.pi/2,
                           epsabs=_EPSABS, epsrel=_EPSREL)[0]

    # Conductance ------------------------------------------------------------

    sigma = sigma_n * (thermal + radiation - 1j*cooper)

    return sigma


# Surface Impedance ----------------------------------------------------------

def surface_impedance(f, d, T, Vgap, method='MB', **kw):
    """Calculate the surface impedance of a superconductor using Mattis-
    Bardeen theory.

    Args:
        f (ndarray): frequency, in units [Hz]
        d (float): superconductor thickness, in units [m]
        T (float): temperature, in units [K]
        Vgap (float): gap voltage, in units [V]
        method (str): 'MB' for Mattis-Bardeen, or 'simple' for the simplified
            surface impedance from Kerr (1996).

    Keyword arguments:
        Tc (float): critical temperature, in units [K]
        Vgap0 (float): gap voltage at T=0K, in units [V]
        sigma_n (float): normal-state conductance, in units [1/ohm*m]
        lambda0 (float): London penetration depth at T=0K, in units [m]

    Returns:
        surface impedance

    """

    # Import keyword arguments (use defaults if not specified)
    tmp = deepcopy(PARAM)
    tmp.update(kw)
    kw = tmp

    # Using Mattis-Bardeen theory...
    if method.lower() == 'mb':
        if isinstance(f, float) or isinstance(f, int):
            return _surface_impedance(f, d, T, Vgap, **kw)
        elif isinstance(f, np.ndarray):
            zs = np.empty_like(f, dtype=complex)
            for i in range(len(f)):
                zs[i] = _surface_impedance(f[i], d, T, Vgap, **kw)
            return zs

    # Using "simple" method from [1]...
    elif method == 'simple':
        dl = _lambda(T, **kw)
        return _surface_impedance_simple(f, d, dl)

    # Method not recognized...
    else:
        raise ValueError("Method not recognized")


def _surface_impedance(f, d, T, Vgap, **kw):
    """Calculate the surface impedance of a superconductor at a single
    frequency point.

    Args:
        f (float): frequency, in units [Hz]
        d (float): superconductor thickness, in units [m]
        T (float): temperature, in units [K]
        Vgap (float): gap voltage, in units [V]
        method (str): 'MB' for Mattis-Bardeen, or 'simple' for the simplified
            surface impedance from Kerr (1996).

    Keyword arguments:
        Tc (float): critical temperature, in units [K]
        Vgap0 (float): gap voltage at T=0K, in units [V]
        sigma_n (float): normal-state conductance, in units [1/ohm*m]
        lambda0 (float): London penetration depth at T=0K, in units [m]

    Returns:
        surface impedance

    """

    # Angular frequency
    w = 2 * sc.pi * f

    # Conductance (using Mattis-Bardeen theory)
    sigma = _conductance(f, T, Vgap, **kw)

    # Surface impedance (Eqn. 5 in [2])
    zs = (np.sqrt(1j * w * sc.mu_0 / sigma) / np.tanh(np.sqrt(1j * w * sc.mu_0 * sigma) * d))

    return zs


def _surface_impedance_simple(f, d, dl):
    """Calculate the surface impedance of a superconductor using the simple
    model presented in [1]. This techniques assumes that the frequency much
    lower than the gap frequency.

    Args:
        f (ndarray): frequency, in units [Hz]
        d (float): superconductor thickness, in units [m]
        dl (float): London penetration depth

    Returns:
        surfance impedance

    """

    # Angular frequency
    w = 2 * sc.pi * f

    # Surface impedance (see Appendix A5 in [1])
    zs = 1j * w * sc.mu_0 * dl / np.tanh(d / dl)

    return zs


# Penetration depths ---------------------------------------------------------

def efield_penetration(zs, f):
    """Calculate the electric field penetration depth.

    Args:
        zs (ndarray): surface impedance
        f (ndarray): frequency, in units [Hz]

    Returns:
        E-field penetration depth

    """

    # Angular frequency
    w = 2 * sc.pi * f

    return zs.imag / (w * sc.mu_0)


def hfield_penetration(zs, f):
    """Calculate the magnetic field penetration depth.

    Args:
        zs (ndarray): surface impedance
        f (ndarray): frequency, in units [Hz]

    Returns:
        H-field penetration depth

    """

    # Angular frequency
    w = 2 * sc.pi * f

    return zs.real / (w * sc.mu_0)


# Lambda ---------------------------------------------------------------------

def _lambda0(Vgap0=None, sigma_n=None, **kw):

    delta = Vgap0 / 2

    return (hbar / sc.pi / sc.mu_0 / sigma_n / delta) ** 0.5


def _lambda(T, **kw):

    t = T / kw['Tc']

    return _lambda0(**kw) / np.sqrt(1 - t ** 4)


# Fermi function -------------------------------------------------------------

def fermi(energy, T):
    """Fermi function.

    Args:
        energy (ndarray): energy in units [eV]
        T (float): temperature in units [K]

    Returns:
        fermi function

    """

    if T != 0.:
        beta = 1 / (kb * T)
        ff = 0.5 * (1 - np.tanh(0.5 * beta * energy))
        return ff
    else:
        return np.heaviside(-energy, 0.5)
