name: linter

on: [push, pull_request]

jobs:
  lint-flake8:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8 environment
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Analysing the code with flake8
        run: |
          flake8 .
